=== epicosy/cna-list/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "version": "1.0.0",
    "type": "object",
    "properties": {
        "id": { "type": "string" },
        "name": { "type": "string" },
        "root": { "type": "string", "format": "email" },
        "email": { "type": "string", "format": "email" },
        "scope": {
            "type": "object",
            "properties": {
                "external": { "type": "boolean" },
                "third_party": { "type": "boolean" },
                "organizations": {
                    "type": "array",
                    "items": { "type": "string" }
                }
            },
            "required": ["external", "third_party", "organizations"]
        },
        "advisories": { "type": "string", "format": "uri" }
    },
    "required": ["id", "name", "root", "email", "scope"]
}

=== epicosy/cna-list/data/ShopBeat.json
{
    "id": "ShopBeat",
    "name": "Shop Beat Solutions (Pty) LTD",
    "root": "cve@mitre.org",
    "email": "support@shopbeat.co.za",
    "scope": {
        "external": false,
        "third_party": true,
        "organizations": [
            "shopbeat"
        ]
    },
    "advisories": "https://www.shopbeat.co.za/security_advisory_location.html"
}

=== epicosy/cna-list/data/Simplinx.json
{
    "id": "Simplinx",
    "name": "Simplinx Ltd.",
    "root": "ics-cert@hq.dhs.gov",
    "email": "security@simplinx.com",
    "scope": {
        "external": false,
        "third_party": false,
        "organizations": [
            "simplinx"
        ]
    },
    "advisories": "https://simplinx.com/en/security-advisories/"
}

=== epicosy/cna-list/cnas/forcepoint.json
{
    "id": "forcepoint",
    "name": "Forcepoint",
    "root": "cve@mitre.org",
    "email": "psirt@forcepoint.com",
    "scope": {
        "external": false,
        "third_party": false,
        "organizations": [
            "forcepoint"
        ]
    },
    "advisories": "https://support.forcepoint.com/s/knowledge-base#t=All&sort=relevancy&f:@sfrecordtypename=[Security%20Advisory]"
}

=== epicosy/cna-list/cnas/certcc.json
{
    "id": "certcc",
    "name": "CERT/CC",
    "email": "cret@cert.org",
    "root": "cve@mitre.org",
    "scope": {
        "external": false,
        "third_party": true,
        "organizations": [
			"apple",
			"microsoft",
			"debian",
			"dell",
			"emc",
			"axis",
			"isc",
			"lenovo",
			"hp",
			"ibm",
			"sonicwall",
			"sap",
			"adobe",
			"intuit",
			"oracle",
			"logitech",
			"novell",
			"corel",
			"cisco",
			"liferay",
			"ge",
			"abb",
			"juniper",
			"foxitsoftware",
			"artifex",
			"rockwellautomation",
			"gnu",
			"vmware",
			"php",
			"xpdfreader",
			"samsung",
			"broadcom",
			"lexmark",
			"siemens",
			"advantech",
			"atvise",
			"schneider-electric",
			"arcinfo",
			"dotcms",
			"forescout",
			"johnsoncontrols",
			"progress",
			"solarwinds",
			"f5",
			"tp-link",
			"smartertools",
			"manageengine",
			"otrs",
			"esri",
			"huawei",
			"fortinet",
			"dlink",
			"zohocorp",
			"freebsd",
			"trendmicro",
			"nlnetlabs",
			"honeywell",
			"apache",
			"nvidia",
			"qnap",
			"avast",
			"zyxel",
			"silabs",
			"att",
			"watchguard",
			"linux",
			"synology",
			"dahuasecurity",
			"moodle",
			"zabbix",
			"silver-peak",
			"autodesk",
			"avg",
			"netgear",
			"navercorp",
			"goabode",
			"avira",
			"ea",
			"alibaba",
			"kingsoft",
			"brocade",
			"toshiba",
			"tianocore",
			"hikvision",
			"linksys",
			"openssl",
			"zte",
			"igniterealtime",
			"google",
			"foscam",
			"westerndigital",
			"zoom",
			"telerik",
			"philips",
			"sierrawireless",
			"hancom",
			"opencv",
			"milesight",
			"lantronix",
			"wso2",
			"hdfgroup",
			"atlassian",
			"chef",
			"crestron",
			"intel",
			"golang",
			"acronis",
			"tibco",
			"pixar",
            "mcafee"
        ]
    },
    "advisories": "https://www.kb.cert.org/vuls/bypublished/desc/"
}

=== epicosy/cna-list/data/OpenBMC.json
{
    "id": "OpenBMC",
    "name": "The OpenBMC Project",
    "root": "cve@mitre.org",
    "email": "openbmc-security@lists.ozlabs.org",
    "scope": {
        "external": false,
        "third_party": false,
        "organizations": [
            "openbmc-project"
        ]
    },
    "advisories": "https://github.com/openbmc/openbmc/security/advisories"
}

=== epicosy/cna-list/cnas/Hillstone.json
{
    "id": "Hillstone",
    "name": "Hillstone Networks Inc.",
    "root": "cve@mitre.org",
    "email": "psirt@hillstonenet.com",
    "scope": {
        "external": false,
        "third_party": false,
        "organizations": [
            "hillstonenet"
        ]
    },
    "advisories": "https://www.hillstonenet.com.cn/support-and-training/psirt/"
}

=== epicosy/cna-list/data/mongodb.json
{
    "id": "mongodb",
    "name": "MongoDB, Inc.",
    "root": "cve@mitre.org",
    "email": "cna@mongodb.com",
    "scope": {
        "external": false,
        "third_party": false,
        "organizations": [
            "mongodb"
        ]
    },
    "advisories": "https://www.mongodb.com/company/contact/mongodb-vulnerability-disclosure-policy"
}

=== epicosy/cna-list/data/Salesforce.json
{
    "id": "Salesforce",
    "name": "Salesforce.com, Inc.",
    "root": "cve@mitre.org",
    "email": "security@salesforce.com",
    "scope": {
        "external": false,
        "third_party": false,
        "organizations": [
            "salesforce",
            "tableau",
            "mulesoft"
        ]
    },
    "advisories": "https://trust.salesforce.com/en/security/security-advisories/"
}
