=== epicosy/cna-list/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "version": "1.0.0",
    "type": "object",
    "properties": {
        "id": { "type": "string" },
        "name": { "type": "string" },
        "root": { "type": "string", "format": "email" },
        "email": { "type": "string", "format": "email" },
        "scope": {
            "type": "object",
            "properties": {
                "external": { "type": "boolean" },
                "third_party": { "type": "boolean" },
                "organizations": {
                    "type": "array",
                    "items": { "type": "string" }
                }
            },
            "required": ["external", "third_party", "organizations"]
        },
        "advisories": { "type": "string", "format": "uri" }
    },
    "required": ["id", "name", "root", "email", "scope"]
}

=== epicosy/cna-list/data/Temporal.json
{
    "id": "Temporal",
    "name": "Temporal Technologies Inc.",
    "root": "cve@mitre.org",
    "email": "security@temporal.io",
    "scope": {
        "external": false,
        "third_party": false,
        "organizations": [
            "temporal"
        ]
    },
    "advisories": "https://docs.temporal.io/temporal-technologies-inc-security"
}

=== epicosy/cna-list/data/Document_Fdn..json
{
    "id": "Document_Fdn.",
    "name": "Document Foundation, The",
    "root": "RootCNA-Coordination@redhat.com",
    "email": "security@documentfoundation.org",
    "scope": {
        "external": false,
        "third_party": false,
        "organizations": [
            "libreoffice"
        ]
    },
    "advisories": "https://www.libreoffice.org/about-us/security/advisories"
}

=== epicosy/cna-list/data/F5.json
{
    "id": "F5",
    "name": "F5, Inc.",
    "root": "cve@mitre.org",
    "email": "f5sirt@f5.com",
    "scope": {
        "external": false,
        "third_party": true,
        "organizations": [
            "f5",
            "nginx"
        ]
    },
    "advisories": "https://support.f5.com/csp/knowledge-center/security"
}

=== epicosy/cna-list/data/Octopus.json
{
    "id": "Octopus",
    "name": "Octopus Deploy",
    "root": "cve@mitre.org",
    "email": "security@octopus.com",
    "scope": {
        "external": false,
        "third_party": false,
        "organizations": [
            "octopus"
        ]
    },
    "advisories": "https://advisories.octopus.com/"
}

=== epicosy/cna-list/data/PSF.json
{
    "id": "PSF",
    "name": "Python Software Foundation",
    "root": "cve@mitre.org",
    "email": "cna@python.org",
    "scope": {
        "external": false,
        "third_party": false,
        "organizations": [
            "python",
            "pypi",
            "pypa"
        ]
    },
    "advisories": "https://mail.python.org/archives/list/security-announce@python.org/latest"
}

=== epicosy/cna-list/data/sap.json
{
    "id": "sap",
    "name": "SAP SE",
    "root": "cve@mitre.org",
    "email": "cna@sap.com",
    "scope": {
        "external": false,
        "third_party": false,
        "organizations": [
            "sap"
        ]
    },
    "advisories": "https://support.sap.com/en/my-support/knowledge-base/security-notes-news.html"
}

=== epicosy/cna-list/data/ZTE.json
{
    "id": "ZTE",
    "name": "ZTE Corporation",
    "root": "cve@mitre.org",
    "email": "psirt@zte.com.cn",
    "scope": {
        "external": false,
        "third_party": false,
        "organizations": [
            "zte"
        ]
    },
    "advisories": "https://support.zte.com.cn/support/news/LoopholeInfoList.aspx?classId=972&_langType=en"
}

=== epicosy/cna-list/data/openEuler.json
{
    "id": "openEuler",
    "name": "openEuler",
    "root": "cve@mitre.org",
    "email": "openeuler-security@openeuler.org",
    "scope": {
        "external": false,
        "third_party": false,
        "organizations": [
            "openeuler"
        ]
    },
    "advisories": "https://www.openeuler.org/en/security/security-bulletins/"
}
