=== epicosy/cna-list/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "version": "1.0.0",
    "type": "object",
    "properties": {
        "id": { "type": "string" },
        "name": { "type": "string" },
        "root": { "type": "string", "format": "email" },
        "email": { "type": "string", "format": "email" },
        "scope": {
            "type": "object",
            "properties": {
                "external": { "type": "boolean" },
                "third_party": { "type": "boolean" },
                "organizations": {
                    "type": "array",
                    "items": { "type": "string" }
                }
            },
            "required": ["external", "third_party", "organizations"]
        },
        "advisories": { "type": "string", "format": "uri" }
    },
    "required": ["id", "name", "root", "email", "scope"]
}

=== epicosy/cna-list/data/PureStorage.json
{
    "id": "PureStorage",
    "name": "Pure Storage, Inc.",
    "root": "cve@mitre.org",
    "email": "psirt@purestorage.com",
    "scope": {
        "external": false,
        "third_party": false,
        "organizations": [
            "purestorage"
        ]
    },
    "advisories": "https://support.purestorage.com/bundle/m_security_bulletins/page/Pure_Security/topics/concept/c_security_bulletins.html"
}

=== epicosy/cna-list/data/elastic.json
{
    "id": "elastic",
    "name": "Elastic",
    "root": "cve@mitre.org",
    "email": "security@elastic.co",
    "scope": {
        "external": false,
        "third_party": false,
        "organizations": [
            "elastic"
        ]
    },
    "advisories": "https://www.elastic.co/community/security"
}

=== epicosy/cna-list/cnas/synology.json
{
    "id": "synology",
    "name": "Synology Inc.",
    "root": "cve@mitre.org",
    "email": "security@synology.com",
    "scope": {
        "external": false,
        "third_party": false,
        "organizations": [
            "synology"
        ]
    },
    "advisories": "https://www.synology.com/en-global/security/advisory"
}

=== epicosy/cna-list/data/GE_Healthcare.json
{
    "id": "GE_Healthcare",
    "name": "GE Healthcare",
    "root": "ics-cert@hq.dhs.gov",
    "email": "GEHealthcareCVD@ge.com",
    "scope": {
        "external": false,
        "third_party": false,
        "organizations": [
            "gehealthcare"
        ]
    },
    "advisories": "https://www.gehealthcare.com/services/lifecycle-management/product-security-portal/security"
}

=== epicosy/cna-list/data/curl.json
{
    "id": "curl",
    "name": "curl",
    "root": "RootCNA-Coordination@redhat.com",
    "email": "cve@curl.se",
    "scope": {
        "external": false,
        "third_party": false,
        "organizations": [
            "haxx"
        ]
    },
    "advisories": "https://curl.se/docs/security.html"
}

=== epicosy/cna-list/data/Genetec.json
{
    "id": "Genetec",
    "name": "Genetec Inc.",
    "root": "cve@mitre.org",
    "email": "security@genetec.com",
    "scope": {
        "external": false,
        "third_party": false,
        "organizations": [
            "genetec"
        ]
    },
    "advisories": "https://resources.genetec.com/security-advisories"
}

=== epicosy/cna-list/cnas/Sophos.json
{
    "id": "Sophos",
    "name": "Sophos Limited",
    "root": "cve@mitre.org",
    "email": "security-alert@sophos.com",
    "scope": {
        "external": false,
        "third_party": false,
        "organizations": [
            "sophos",
            "capsule8"
        ]
    },
    "advisories": "https://community.sophos.com/b/security-blog/"
}

=== epicosy/cna-list/cnas/Swift.json
{
    "id": "Swift",
    "name": "Swift Project",
    "root": "cve@mitre.org",
    "email": "cve@forums.swift.org",
    "scope": {
        "external": false,
        "third_party": false,
        "organizations": [
            "apple"
        ]
    },
    "advisories": "https://www.swift.org/support/security.html"
}
